'use client';
import { useRef, useState } from 'react';
import { toast } from 'sonner';
import { Button, Input, Select, Textarea } from '@/components/ui';
import { api, json } from '@/lib/api/client';
import { groupLabels, money, needsBase, type Config, type Match, type Question, type Settings } from '@/lib/car-recommendations';
import { Field, Panel } from './shared';
export default function ConfigForm({ settings, writable, saved }: { settings: Settings; writable: boolean; saved: () => void }) {
  const [config, setConfig] = useState<Config>(() => structuredClone(settings.config)), [enabled, setEnabled] = useState(settings.enabled), [retention, setRetention] = useState(settings.retentionDays);
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [restore, setRestore] = useState(false), [preview, setPreview] = useState<Match[] | null>(null), [previewBudget, setPreviewBudget] = useState(500000000), [previewPurpose, setPreviewPurpose] = useState('family');
  const lock = useRef(false), totalWeight = Object.values(config.weights).reduce((sum, n) => sum + n, 0);
  const changeQuestion = (index: number, patch: Partial<Question>) => setConfig(old => ({ ...old, questions: old.questions.map((q, i) => i === index ? { ...q, ...patch } : q) }));
  const move = (index: number, direction: number) => setConfig(old => { const questions = [...old.questions]; [questions[index], questions[index + direction]] = [questions[index + direction], questions[index]]; return { ...old, questions }; });
  const execute = async (previewOnly = false) => {
    if (lock.current) return; lock.current = true; setBusy(true); setError('');
    try {
      if (previewOnly) {
        const extras = Object.fromEntries(config.questions.filter(q => q.key.startsWith('custom_') && q.enabled && q.required).map(q => [q.key, q.type === 'multi' ? [q.options[0].key] : q.options[0].key]));
        const result = await api<{ results: Match[] }>(`${needsBase}/preview`, json('POST', { config, answers: { purposes: [previewPurpose], budget: { min: config.minBudget, max: previewBudget }, passengers: '3_5', requireSeats: false, environment: 'city', priorities: ['space'].slice(0, config.questions.find(q => q.key === 'priorities')!.maxSelections), technical: { required: [] }, extras, ...(config.questions.find(q => q.key === 'style')?.required ? { style: 'practical' } : {}) } })); setPreview(result.results);
      } else {
        await api(`${needsBase}/settings`, json('PUT', { expectedUpdatedAt: settings.updatedAt, enabled, retentionDays: retention, config })); toast.success('Đã lưu cấu hình và áp dụng cho khảo sát mới.'); saved();
      }
    } catch (failure) { setError(failure instanceof Error ? failure.message : 'Không thể lưu.'); }
    finally { lock.current = false; setBusy(false); }
  };
  return <form className="space-y-5" onSubmit={e => { e.preventDefault(); if (writable) void execute(); }}>
    <Panel><h2 className="text-xl font-bold">Cấu hình hiện hành</h2><p className="my-3 text-sm text-[var(--muted-fg)]">Lưu thay đổi áp dụng cho khảo sát mới. Câu trả lời và kết quả trong lịch sử giữ nguyên. Các mã dùng chấm điểm được bảo vệ.</p>
      <fieldset disabled={!writable || busy} className="space-y-4"><label className="flex items-center gap-3"><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)} />Bật tiện ích Mua xe theo nhu cầu</label><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Field label="Thời hạn lưu (ngày)"><Input type="number" min={1} max={730} value={retention} required onChange={e => setRetention(Number(e.target.value))} /></Field>
        <Field label="Ngân sách thấp nhất (đ)"><Input type="number" min={0} max={50000000000} value={config.minBudget} required onChange={e => setConfig(old => ({ ...old, minBudget: Number(e.target.value) }))} /></Field>
        <Field label="Ngân sách cao nhất (đ)"><Input type="number" min={1} max={50000000000} value={config.maxBudget} required onChange={e => setConfig(old => ({ ...old, maxBudget: Number(e.target.value) }))} /></Field>
        <Field label="Giới hạn tổng xe đề xuất"><Input type="number" min={1} max={5000} value={config.maxResults} required onChange={e => setConfig(old => ({ ...old, maxResults: Number(e.target.value) }))} /><span className="text-xs text-[var(--muted-fg)]">Trang web hiển thị 6 xe mỗi lần tải.</span></Field>
      </div></fieldset><p className="mt-3 text-xs text-[var(--muted-fg)]">Retention được thực thi bằng lịch chạy lệnh prune trên server. Rút ngắn sẽ xóa phiên cũ vượt thời hạn ở lần chạy kế tiếp.</p>
    </Panel>
    <Panel><h2 className="text-lg font-semibold">Trọng số và cách chấm điểm</h2><fieldset disabled={!writable || busy} className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(groupLabels).map(([key, label]) => <Field key={key} label={`${label} (%)`}><Input type="number" min={key === 'budget' ? 1 : 0} max={100} value={config.weights[key as keyof typeof groupLabels]} required onChange={e => setConfig(old => ({ ...old, weights: { ...old.weights, [key]: Number(e.target.value) } }))} /></Field>)}</fieldset><p className={`mt-3 font-semibold ${totalWeight !== 100 ? 'text-red-600' : ''}`}>Tổng trọng số: {totalWeight}% / 100%</p>
      <div className="mt-4 space-y-2 text-sm text-[var(--muted-fg)]"><p>Điểm nhóm 0–100, nhân trọng số và tỷ lệ dữ liệu có nguồn. Không biết = 0; không tự suy tính năng từ hãng xe. Không chọn kỹ thuật thì bỏ trọng số nhóm đó khỏi mẫu số.</p><p>Ngân sách trong khoảng = 100, dưới min = 80; vượt max loại ngay. Số ghế đủ nhóm = 100, thiếu ghế khi không bắt buộc giảm theo tỷ lệ. Assessment 1/2/3/4/5 → 0/25/50/75/100. Ưu tiên hạng 1/2/3 có hệ số 3/2/1.</p><p>Ví dụ chỉ biết giá trong khoảng và đủ ghế, không chọn kỹ thuật: điểm và dữ liệu khoảng <strong>{Math.round((config.weights.budget + config.weights.seats) / Math.max(1, 100 - config.weights.technical) * 100)}%</strong>. Phong cách và câu hỏi bổ sung chỉ lưu tham khảo.</p></div>
    </Panel>
    <Panel><h2 className="text-lg font-semibold">Câu hỏi và thứ tự</h2><div className="mt-4 space-y-3">{config.questions.map((q, index) => {
      const custom = q.key.startsWith('custom_'), core = !custom && !['technical', 'style'].includes(q.key);
      return <details className="tt-needs-question" key={q.key}><summary className="cursor-pointer font-semibold">{index + 1}. {q.title} {q.enabled ? '' : '(đang ẩn)'}</summary><fieldset disabled={!writable || busy} className="mt-4 space-y-4">
        <div className="flex flex-wrap items-center gap-2"><span className="mr-auto text-xs text-[var(--muted-fg)]">Mã: {q.key}{custom ? ' · Câu hỏi tham khảo' : ' · Giữ nguyên mã scoring'}</span><Button type="button" variant="secondary" size="sm" aria-label={`Đưa câu ${index + 1} lên`} disabled={!index} onClick={() => move(index, -1)}>↑</Button><Button type="button" variant="secondary" size="sm" aria-label={`Đưa câu ${index + 1} xuống`} disabled={index === config.questions.length - 1} onClick={() => move(index, 1)}>↓</Button>{custom && <Button type="button" variant="ghost" size="sm" onClick={() => { if (confirm('Bỏ câu hỏi này khỏi khảo sát mới? Lịch sử cũ vẫn giữ nguyên.')) setConfig(old => ({ ...old, questions: old.questions.filter(item => item.key !== q.key) })); }}>Bỏ câu hỏi</Button>}</div>
        <Field label="Tiêu đề câu hỏi"><Input value={q.title} maxLength={240} required onChange={e => changeQuestion(index, { title: e.target.value })} /></Field><Field label="Mô tả"><Textarea rows={2} maxLength={1000} value={q.description} onChange={e => changeQuestion(index, { description: e.target.value })} /></Field><Field label="Hướng dẫn / lưu ý"><Textarea rows={2} maxLength={1000} value={q.helpText} onChange={e => changeQuestion(index, { helpText: e.target.value })} /></Field>
        <div className="flex flex-wrap items-center gap-5"><label className="flex items-center gap-2"><input type="checkbox" disabled={core} checked={q.enabled} onChange={e => changeQuestion(index, { enabled: e.target.checked, required: e.target.checked ? q.required : false })} />Hiển thị</label><label className="flex items-center gap-2"><input type="checkbox" disabled={core || q.key === 'technical' || !q.enabled} checked={q.required} onChange={e => changeQuestion(index, { required: e.target.checked })} />Bắt buộc</label>{q.type === 'multi' && <Field label="Số lựa chọn tối đa"><Select value={q.maxSelections} onChange={e => changeQuestion(index, { maxSelections: Number(e.target.value) })}>{Array.from({ length: q.key === 'purposes' ? 2 : 3 }, (_, i) => <option key={i + 1} value={i + 1}>{i + 1}</option>)}</Select></Field>}{custom && <Field label="Kiểu lựa chọn"><Select value={q.type} onChange={e => changeQuestion(index, { type: e.target.value as Question['type'], maxSelections: 1 })}><option value="single">Một lựa chọn</option><option value="multi">Nhiều lựa chọn</option></Select></Field>}</div>
        {q.options.length > 0 && <div className="space-y-3"><h3 className="text-sm font-medium">Lựa chọn</h3>{q.options.map((option, i) => <div key={i} className="grid gap-2 sm:grid-cols-[minmax(110px,.6fr)_minmax(0,1.4fr)_auto]"><Input aria-label={`Mã lựa chọn ${i + 1}`} disabled={!custom} value={option.key} maxLength={40} onChange={e => changeQuestion(index, { options: q.options.map((o, n) => n === i ? { ...o, key: e.target.value } : o) })} /><Input aria-label={`Nhãn lựa chọn ${i + 1}`} value={option.label} required maxLength={160} onChange={e => changeQuestion(index, { options: q.options.map((o, n) => n === i ? { ...o, label: e.target.value } : o) })} />{custom && <Button type="button" size="sm" variant="ghost" disabled={q.options.length <= 1} onClick={() => changeQuestion(index, { options: q.options.filter((_, n) => n !== i) })}>Bỏ</Button>}</div>)}{custom && <Button type="button" variant="secondary" size="sm" disabled={q.options.length >= 20} onClick={() => changeQuestion(index, { options: [...q.options, { key: `option_${Date.now().toString(36)}`, label: 'Lựa chọn mới' }] })}>Thêm lựa chọn</Button>}</div>}
      </fieldset></details>;
    })}</div>{writable && <Button type="button" variant="secondary" className="mt-4" disabled={busy || config.questions.length >= 20} onClick={() => setConfig(old => ({ ...old, questions: [...old.questions, { key: `custom_${Date.now().toString(36)}`, title: 'Câu hỏi tham khảo mới', description: '', helpText: 'Chỉ lưu tham khảo, không dùng chấm điểm.', type: 'single', required: false, enabled: true, maxSelections: 1, options: [{ key: 'option_1', label: 'Lựa chọn 1' }] }] }))}>Thêm câu hỏi tham khảo</Button>}</Panel>
    <Panel><h2 className="text-lg font-semibold">Mốc ngân sách gợi ý</h2><fieldset disabled={!writable || busy} className="mt-4 space-y-3">{config.budgetPresets.map((preset, i) => <div className="grid gap-3 sm:grid-cols-[1fr_1fr_1fr_auto]" key={i}>{(['label', 'min', 'max'] as const).map(key => <Field key={key} label={key === 'label' ? 'Tên mốc' : key === 'min' ? 'Từ (đ)' : 'Đến (đ)'}><Input type={key === 'label' ? 'text' : 'number'} value={preset[key]} required onChange={e => setConfig(old => ({ ...old, budgetPresets: old.budgetPresets.map((p, n) => n === i ? { ...p, [key]: key === 'label' ? e.target.value : Number(e.target.value) } : p) }))} /></Field>)}<Button type="button" variant="ghost" className="self-end" onClick={() => setConfig(old => ({ ...old, budgetPresets: old.budgetPresets.filter((_, n) => n !== i) }))}>Bỏ</Button></div>)}<Button type="button" variant="secondary" disabled={config.budgetPresets.length >= 12} onClick={() => setConfig(old => ({ ...old, budgetPresets: [...old.budgetPresets, { label: 'Mốc mới', min: old.minBudget, max: old.maxBudget }] }))}>Thêm mốc ngân sách</Button></fieldset></Panel>
    <Panel><h2 className="text-lg font-semibold">Xem thử xếp hạng theo cấu hình trên form</h2><p className="my-3 text-sm text-[var(--muted-fg)]">Dùng kho thật với 5 người, đô thị, ưu tiên rộng rãi; không yêu cầu ghế/kỹ thuật. Không lưu khảo sát hoặc thay đổi cấu hình.</p><div className="grid gap-3 sm:grid-cols-3"><Field label="Ngân sách tối đa xem thử"><Input type="number" min={1} max={config.maxBudget} value={previewBudget} onChange={e => setPreviewBudget(Number(e.target.value))} /></Field><Field label="Mục đích xem thử"><Select value={previewPurpose} onChange={e => setPreviewPurpose(e.target.value)}>{config.questions.find(q => q.key === 'purposes')?.options.map(o => <option key={o.key} value={o.key}>{o.label}</option>)}</Select></Field><Button type="button" variant="secondary" className="self-end" disabled={busy || totalWeight !== 100} onClick={() => void execute(true)}>Xem thử xếp hạng</Button></div>
      {preview && <div className="mt-4 space-y-3">{!preview.length && <p>Chưa có xe đáp ứng điều kiện xem thử.</p>}{preview.map(item => <details className="tt-needs-question" key={item.car.id}><summary className="cursor-pointer">{item.car.name} · {money(item.car.price)} · <strong>{item.score}/100</strong> · dữ liệu {item.coverage}%</summary><div className="mt-3 space-y-2 text-sm">{item.components.map(c => <p key={c.key}>{groupLabels[c.key]}: {c.score.toFixed(1)}/100 × trọng số {c.weight}% × dữ liệu {(c.coverage * 100).toFixed(0)}%</p>)}</div></details>)}</div>}
    </Panel>
    {error && <Panel><p role="alert" className="text-red-600">{error}</p><p className="mt-2 text-sm">Nếu dữ liệu đã được người khác sửa, dùng Làm mới rồi đối chiếu lại trước khi lưu.</p></Panel>}
    {writable && <Panel><div className="flex flex-wrap justify-end gap-3"><Button type="button" variant="secondary" disabled={busy} onClick={() => setRestore(true)}>Khôi phục giá trị mặc định</Button><Button type="submit" disabled={busy || totalWeight !== 100}>{busy ? 'Đang xử lý…' : 'Lưu thay đổi'}</Button></div>{restore && <div role="alert" className="mt-4 space-y-3 border-t border-[var(--border-color)] pt-4"><p>Khôi phục câu hỏi, mốc ngân sách và trọng số mặc định trên form? Câu hỏi bổ sung sẽ được bỏ khỏi cấu hình mới; lịch sử và hồ sơ xe giữ nguyên. Bấm Lưu thay đổi sau khi kiểm tra để áp dụng.</p><div className="flex gap-3"><Button type="button" variant="secondary" onClick={() => setRestore(false)}>Hủy</Button><Button type="button" onClick={() => { setConfig(structuredClone(settings.defaults)); setPreview(null); setRestore(false); }}>Khôi phục mặc định</Button></div></div>}</Panel>}
  </form>;
}
