'use client';
import { useState } from 'react';
import { BarChart3, ClipboardCheck, Eye, MousePointer, Phone } from 'lucide-react';
import { Button, DataTable, Input, StatsCard, StatusBadge } from '@/components/ui';
import { query } from '@/lib/api/client';
import { defaultDateRange, needsBase, type Overview as OverviewData } from '@/lib/car-recommendations';
import { formatDate } from '@/lib/date';
import { Field, LoadState, Panel, useNeedsData } from './shared';
const bucketLabels: Record<string, string> = { under300: 'Đến 300 triệu', '300to500': 'Trên 300–500 triệu', '500to800': 'Trên 500–800 triệu', '800to1000': 'Trên 800 triệu–1 tỷ', over1000: 'Trên 1 tỷ' };
const distributions = { purposes: 'Mục đích mua xe', priorities: 'Các ưu tiên', passengers: 'Số người thường đi', environment: 'Môi trường', brand: 'Hãng mong muốn', bodyStyle: 'Kiểu dáng', transmission: 'Hộp số', fuel: 'Nhiên liệu' };
export default function Overview({ revision }: { revision: number }) {
  const [draft, setDraft] = useState(defaultDateRange), [range, setRange] = useState(defaultDateRange), [retry, setRetry] = useState(0);
  const resource = useNeedsData<OverviewData>(`${needsBase}/overview${query(range)}`, revision + retry), data = resource.data;
  const renderBars = (rows: { key: string; count: number; unmet: number }[], label: (key: string) => string, unmet = false) => {
    const selected = rows.filter(row => (unmet ? row.unmet : row.count) > 0), max = Math.max(1, ...selected.map(row => unmet ? row.unmet : row.count));
    return selected.length ? <div className="tt-needs-bars">{selected.map(row => <div key={row.key}><div className="mb-1 flex justify-between gap-3 text-sm"><span>{label(row.key)}</span><strong>{unmet ? row.unmet : row.count} phiên</strong></div><progress aria-label={label(row.key)} value={unmet ? row.unmet : row.count} max={max} /></div>)}</div> : <p className="mt-4 text-[var(--muted-fg)]">Chưa có dữ liệu.</p>;
  };
  return <div className="space-y-5">
    <Panel><form className="tt-needs-filters" onSubmit={e => { e.preventDefault(); setRange(draft); }}><Field label="Từ ngày"><Input type="date" value={draft.from} onChange={e => setDraft(old => ({ ...old, from: e.target.value }))} required /></Field><Field label="Đến ngày"><Input type="date" value={draft.to} onChange={e => setDraft(old => ({ ...old, to: e.target.value }))} required /></Field><Button type="submit">Xem thống kê</Button></form><p className="mt-3 text-sm text-[var(--muted-fg)]">Theo ngày Việt Nam, tối đa 366 ngày. Mặc định 30 ngày gần nhất.</p></Panel>
    <LoadState {...resource} retry={() => setRetry(n => n + 1)} />
    {data && <>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatsCard title="Khảo sát hoàn tất" value={data.total} icon={<ClipboardCheck />} /><StatsCard title="Phiên xem kết quả" value={data.viewed} icon={<Eye />} color="blue" /><StatsCard title="Phiên bấm xem xe" value={data.carClicked} icon={<MousePointer />} color="green" /><StatsCard title="Phiên bấm liên hệ" value={data.contactClicked} icon={<Phone />} color="amber" /><StatsCard title="Chưa có xe phù hợp" value={data.empty} icon={<BarChart3 />} /></div>
      <Panel><p className="text-sm">Trong <strong>{data.total} phiên</strong> tạo từ {formatDate(data.range.from)} đến {formatDate(data.range.to)}: xem kết quả <strong>{data.rates.viewed}%</strong> · xem xe <strong>{data.rates.carClicked}%</strong> · liên hệ <strong>{data.rates.contactClicked}%</strong> · chưa có xe <strong>{data.rates.empty}%</strong>.</p><p className="mt-2 text-sm text-[var(--muted-fg)]">Mỗi tỷ lệ dùng số phiên hoàn tất làm mẫu số. Các tương tác được tính cho những phiên này, kể cả xảy ra sau khoảng ngày. Một người có thể làm nhiều khảo sát; số liệu thể hiện nhu cầu và tương tác.</p>{!data.total && <p className="mt-3 font-medium">Chưa có khảo sát trong khoảng ngày này.</p>}</Panel>
      <div className="grid gap-4 lg:grid-cols-2"><Panel><h2 className="text-lg font-semibold">Ngân sách tối đa khách chọn</h2>{renderBars(data.budgets, key => bucketLabels[key] || key)}</Panel><Panel><h2 className="text-lg font-semibold">Ngân sách chưa có xe đáp ứng</h2>{renderBars(data.budgets, key => bucketLabels[key] || key, true)}</Panel></div>
      <div className="grid gap-4 lg:grid-cols-2">{Object.entries(distributions).map(([field, title]) => <Panel key={field}><h2 className="text-lg font-semibold">{title}</h2>{renderBars(data.distributions.filter(row => row.field === field), key => key === 'unspecified' ? 'Không quan trọng' : data.labels[field]?.[key] || key)}{['purposes', 'priorities'].includes(field) && <p className="mt-3 text-xs text-[var(--muted-fg)]">Một phiên có thể chọn nhiều mục; tổng lựa chọn có thể lớn hơn số phiên.</p>}</Panel>)}</div>
      <Panel><h2 className="text-lg font-semibold">Nhu cầu chưa được đáp ứng</h2><p className="mt-2 text-sm text-[var(--muted-fg)]">Chỉ gồm {data.empty} phiên không có kết quả. Đây là nhu cầu được ghi nhận, chưa đủ để kết luận nguyên nhân thiếu xe.</p><div className="grid gap-6 md:grid-cols-3">{['purposes', 'passengers', 'priorities'].map(field => <div key={field}><h3 className="mt-4 font-medium">{distributions[field as keyof typeof distributions]}</h3>{renderBars(data.distributions.filter(row => row.field === field), key => data.labels[field]?.[key] || key, true)}</div>)}</div></Panel>
      <Panel><h2 className="text-lg font-semibold">Xu hướng khảo sát theo ngày</h2><div className="tt-needs-trend mt-4" role="img" aria-label="Số phiên khảo sát mỗi ngày; bảng chi tiết bên dưới">{data.trend.map(row => <div key={row.day} title={`${formatDate(row.day)}: ${row.count} phiên, ${row.unmet} chưa có xe`}><span style={{ height: `${Math.max(1, row.count / Math.max(1, ...data.trend.map(item => item.count)) * 100)}%` }} /></div>)}</div><details className="mt-3"><summary className="cursor-pointer text-sm text-red-600">Xem số liệu từng ngày</summary><div className="mt-3 max-h-72 overflow-auto"><table className="w-full text-sm"><caption className="sr-only">Khảo sát theo ngày Việt Nam</caption><thead><tr><th className="p-2 text-left">Ngày</th><th>Khảo sát</th><th>Chưa có xe</th></tr></thead><tbody>{data.trend.map(row => <tr key={row.day}><td className="p-2">{formatDate(row.day)}</td><td className="text-center">{row.count}</td><td className="text-center">{row.unmet}</td></tr>)}</tbody></table></div></details></Panel>
      {([['topCars', 'Xe được đề xuất nhiều nhất'], ['topClicked', 'Xe được bấm xem nhiều nhất']] as const).map(([key, title]) => <div key={key}><h2 className="mb-3 text-lg font-semibold">{title}</h2><DataTable data={data[key].map(car => ({ ...car, id: car.car_id }))} columns={[
        { key: 'name', label: 'Xe' }, { key: 'recommendations', label: 'Phiên được đề xuất' }, { key: 'clicks', label: 'Phiên bấm xem' }, { key: 'clickRate', label: 'Tỷ lệ', render: row => `${row.clickRate}%` }, { key: 'status', label: 'Kho hiện tại', render: row => row.removed || !row.status ? 'Đã xóa' : <StatusBadge status={row.status} /> },
      ]} emptyMessage="Chưa có dữ liệu tương ứng." /><p className="mt-2 text-xs text-[var(--muted-fg)]">Tỷ lệ từng xe = số phiên bấm xem xe / số phiên có xe trong đề xuất. Trạng thái kho là hiện tại, số đề xuất là lịch sử. Tối đa 20 xe mỗi bảng.</p></div>)}
    </>}
  </div>;
}
