'use client';
import { useRef, useState } from 'react';
import { toast } from 'sonner';
import { Button, DataTable, Select, StatusBadge, Textarea } from '@/components/ui';
import { api, json, query, type PageResult } from '@/lib/api/client';
import { money, needsBase, type Assessment, type ProfileDetail, type ProfileRow, type Settings } from '@/lib/car-recommendations';
import { formatDate } from '@/lib/date';
import { Field, LoadState, Panel, useNeedsData } from './shared';
export default function Profiles({ settings, writable, revision }: { settings: Settings; writable: boolean; revision: number }) {
  const [filters, setFilters] = useState({ brandId: '', modelId: '', status: '', missing: '' }), [search, setSearch] = useState(''), [page, setPage] = useState(1), [retry, setRetry] = useState(0), [selected, setSelected] = useState<ProfileRow[]>([]), [editing, setEditing] = useState<ProfileRow[] | null>(null);
  const resource = useNeedsData<PageResult<ProfileRow>>(`${needsBase}/car-profiles${query({ ...filters, page, limit: 10, search })}`, revision + retry);
  const update = (key: keyof typeof filters, value: string) => { setFilters(old => ({ ...old, [key]: value, ...(key === 'brandId' ? { modelId: '' } : {}) })); setPage(1); setSelected([]); };
  if (editing) return editing.length === 1 ? <SingleProfile row={editing[0]} settings={settings} writable={writable} close={() => setEditing(null)} saved={() => { setEditing(null); setSelected([]); setRetry(n => n + 1); }} /> : <ProfileEditor rows={editing} settings={settings} writable={writable} initial={{}} close={() => setEditing(null)} saved={() => { setEditing(null); setSelected([]); setRetry(n => n + 1); }} />;
  return <div className="space-y-5"><Panel><p className="mb-4 text-sm text-[var(--muted-fg)]">Đánh giá đúng từng xe trong kho. Tiêu chí chưa có căn cứ để “Chưa rõ”; không gán điểm theo thương hiệu.</p><div className="tt-needs-filters"><Field label="Hãng xe"><Select value={filters.brandId} onChange={e => update('brandId', e.target.value)}><option value="">Tất cả hãng</option>{settings.catalogs.brands.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</Select></Field><Field label="Dòng xe"><Select value={filters.modelId} onChange={e => update('modelId', e.target.value)}><option value="">Tất cả dòng</option>{settings.catalogs.models.filter(m => !filters.brandId || m.brandId === filters.brandId).map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</Select></Field><Field label="Trạng thái kho"><Select value={filters.status} onChange={e => update('status', e.target.value)}><option value="">Tất cả</option><option value="active">Đang bán</option><option value="deposit">Đã cọc</option><option value="sold">Đã bán</option><option value="inactive">Đang ẩn</option></Select></Field><Field label="Mức đủ thông tin"><Select value={filters.missing} onChange={e => update('missing', e.target.value)}><option value="">Tất cả</option><option value="true">Còn tiêu chí chưa rõ</option><option value="false">Đã đánh giá đủ</option></Select></Field></div></Panel>
    {writable && <div className="flex flex-wrap items-center justify-end gap-3"><span className="text-sm">Đã chọn {selected.length}/50 xe</span><Button variant="secondary" disabled={!selected.length} onClick={() => setSelected([])}>Bỏ chọn</Button><Button disabled={selected.length < 2} onClick={() => setEditing(selected)}>Đánh giá các xe đã chọn</Button></div>}
    <LoadState {...resource} retry={() => setRetry(n => n + 1)} />
    {!resource.error && <DataTable<ProfileRow> data={resource.data?.data || []} searchPlaceholder="Tìm tên xe…" emptyMessage={resource.loading ? 'Đang tải…' : 'Không có xe phù hợp.'} remote={{ page, perPage: 10, total: resource.data?.meta.total || 0, search, onPage: setPage, onSearch: value => { setSearch(value); setPage(1); setSelected([]); } }} onView={row => setEditing([row])} columns={[
      ...(writable ? [{ key: 'select', label: 'Chọn', render: (row: ProfileRow) => <input type="checkbox" aria-label={`Chọn xe ${row.name}`} checked={selected.some(item => item.id === row.id)} disabled={selected.length >= 50 && !selected.some(item => item.id === row.id)} onChange={e => setSelected(old => e.target.checked ? [...old, row] : old.filter(item => item.id !== row.id))} /> }] : []),
      { key: 'name', label: 'Xe', render: row => <div><strong>{row.name}</strong><p className="text-xs text-[var(--muted-fg)]">{row.brand} · {row.model} · {row.year}</p></div> }, { key: 'price', label: 'Giá niêm yết', render: row => <span className="whitespace-nowrap">{money(row.price)}</span> }, { key: 'status', label: 'Kho', render: row => <div><StatusBadge status={row.status} /><p className="mt-1 text-xs">{row.publishedAt ? 'Đã công khai' : 'Chưa công khai'}</p></div> }, { key: 'knownCount', label: 'Tiêu chí có căn cứ', render: row => `${row.knownCount}/${settings.assessmentCatalog.length}` }, { key: 'updatedAt', label: 'Cập nhật', render: row => row.updatedAt ? formatDate(row.updatedAt) : 'Chưa đánh giá' },
    ]} />}
  </div>;
}
function SingleProfile({ row, settings, writable, close, saved }: { row: ProfileRow; settings: Settings; writable: boolean; close: () => void; saved: () => void }) {
  const [retry, setRetry] = useState(0), resource = useNeedsData<ProfileDetail>(`${needsBase}/car-profiles/${row.id}`, retry);
  return resource.data ? <ProfileEditor key={resource.data.updatedAt || 'new'} rows={[{ ...row, updatedAt: resource.data.updatedAt }]} settings={settings} initial={resource.data.assessments} writable={writable} close={close} saved={saved} /> : <div className="space-y-4"><Button variant="secondary" onClick={close}>← Quay lại danh sách xe</Button><LoadState {...resource} retry={() => setRetry(n => n + 1)} /></div>;
}
function ProfileEditor({ rows, settings, initial, writable, close, saved }: { rows: ProfileRow[]; settings: Settings; initial: Record<string, Assessment>; writable: boolean; close: () => void; saved: () => void }) {
  const [assessments, setAssessments] = useState(() => structuredClone(initial)), [busy, setBusy] = useState(false), [error, setError] = useState(''), [confirmed, setConfirmed] = useState(false), lock = useRef(false), batch = rows.length > 1;
  const save = async () => {
    if (lock.current) return; lock.current = true; setBusy(true); setError('');
    try {
      if (batch) await api(`${needsBase}/car-profiles/batch`, json('PUT', { items: rows.map(row => ({ carId: row.id, expectedUpdatedAt: row.updatedAt, assessments, merge: true })) }));
      else await api(`${needsBase}/car-profiles/${rows[0].id}`, json('PUT', { expectedUpdatedAt: rows[0].updatedAt, assessments }));
      toast.success(`Đã lưu đánh giá ${rows.length} xe.`); saved();
    } catch (failure) { setError(failure instanceof Error ? failure.message : 'Không thể lưu.'); }
    finally { setBusy(false); lock.current = false; }
  };
  return <form className="space-y-5" onSubmit={e => { e.preventDefault(); if (writable) void save(); }}><Button type="button" variant="secondary" disabled={busy} onClick={close}>← Quay lại danh sách xe</Button><Panel><h2 className="text-xl font-bold">{batch ? `Đánh giá ${rows.length} xe đã chọn` : rows[0].name}</h2>{batch && <p className="my-3 text-sm">{rows.map(row => row.name).join(' · ')}</p>}<p className="mt-3 text-sm text-[var(--muted-fg)]">1 = ít phù hợp, 2 = hạn chế, 3 = trung bình, 4 = phù hợp, 5 = rất phù hợp theo căn cứ ghi bên cạnh. Chưa rõ không tính điểm. Đánh giá có hiệu lực cho khảo sát mới.</p>{batch && <p className="mt-2 text-sm">Chỉ áp dụng tiêu chí bạn nhập cho các xe được chọn; các đánh giá khác của từng xe giữ nguyên.</p>}</Panel>
    <fieldset disabled={!writable || busy} className="space-y-5">{[['purposes', 'Mục đích sử dụng'], ['environment', 'Môi trường di chuyển'], ['priorities', 'Các ưu tiên']].map(([group, title]) => <Panel key={group}><h3 className="text-lg font-semibold">{title}</h3>{settings.assessmentCatalog.filter(item => item.group === group).map(item => <div className="tt-needs-factors" key={item.key}><div><strong className="text-sm">{item.label}</strong><p className="mt-2 text-xs text-[var(--muted-fg)]">{item.guidance}</p></div><Field label={`Điểm ${item.label}`}><Select value={assessments[item.key]?.score || ''} onChange={e => setAssessments(old => { const copy = { ...old }; if (e.target.value) copy[item.key] = { score: Number(e.target.value), source: old[item.key]?.source || '' }; else delete copy[item.key]; return copy; })}><option value="">Chưa rõ</option>{[1, 2, 3, 4, 5].map(n => <option key={n} value={n}>{n}/5</option>)}</Select></Field><Field label={`Căn cứ ${item.label}`}><Textarea rows={3} disabled={!assessments[item.key]} minLength={3} maxLength={1000} required={!!assessments[item.key]} placeholder="Nguồn, ngày kiểm tra, số liệu đúng xe…" value={assessments[item.key]?.source || ''} onChange={e => setAssessments(old => ({ ...old, [item.key]: { ...old[item.key], source: e.target.value } }))} /></Field></div>)}</Panel>)}</fieldset>
    {error && <Panel><p className="text-red-600" role="alert">{error}</p><p className="mt-2 text-sm">Quay lại danh sách và mở lại hồ sơ để lấy cập nhật mới nhất. Lưu hàng loạt thất bại sẽ không lưu bất kỳ xe nào.</p></Panel>}
    {writable && <Panel>{batch && <label className="mb-4 flex items-start gap-3 text-sm"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} required /><span>Tôi đã đối chiếu các căn cứ đã nhập với từng xe được chọn.</span></label>}<div className="flex justify-end"><Button type="submit" disabled={busy || batch && (!confirmed || !Object.keys(assessments).length)}>{busy ? 'Đang lưu…' : 'Lưu đánh giá'}</Button></div></Panel>}
  </form>;
}
