'use client';
import { useEffect, useRef, useState } from 'react';
import { toast } from 'sonner';
import { Button, DataTable, Input, Select, type Column } from '@/components/ui';
import { Field } from '@/components/auspicious-date/Editor';
import { api, json, query, type PageResult } from '@/lib/api/client';
import { baseTypeLabels, categoryLabels, leadStatusLabels, money, scopeLabels, valuationBase as base, type Catalog, type ValuationRecord, type ValuationRecordDetail } from '@/lib/valuation';
const dateTime = (value: string) => new Intl.DateTimeFormat('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh', dateStyle: 'short', timeStyle: 'short' }).format(new Date(value));
const range = (min: number | null, max: number | null) => min === null || max === null ? '—' : `${money(min)} – ${money(max)}`;
const resultLabels: Record<string, string> = { ESTIMATED: 'Có giá tham khảo', MANUAL_INSPECTION: 'Cần kiểm định', MISSING_REFERENCE: 'Thiếu giá tham chiếu', INSUFFICIENT_DATA: 'Thiếu quy tắc' };
const conditionFields = { exteriorCondition: ['EXTERIOR', 'Ngoại thất'], interiorCondition: ['INTERIOR', 'Nội thất'], accidentLevel: ['ACCIDENT', 'Tai nạn'], floodLevel: ['FLOOD', 'Ngập nước'], engineCondition: ['ENGINE', 'Động cơ'], transmissionCondition: ['TRANSMISSION', 'Hộp số'], serviceHistory: ['SERVICE', 'Bảo dưỡng'], usageType: ['USAGE', 'Mục đích sử dụng'] };
const blankFilters = { dateFrom: '', dateTo: '', brandId: '', modelId: '', leadStatus: '', priceMin: '', priceMax: '' };
export default function History({ catalog, canUpdate }: { catalog: Catalog; canUpdate: boolean }) {
  const [draft, setDraft] = useState(blankFilters), [filters, setFilters] = useState(blankFilters), [page, setPage] = useState(1), [search, setSearch] = useState(''), [term, setTerm] = useState('');
  const [rows, setRows] = useState<PageResult<ValuationRecord> | null>(null), [error, setError] = useState(''), [loading, setLoading] = useState(false), [reload, setReload] = useState(0);
  const [selected, setSelected] = useState(''), [detail, setDetail] = useState<ValuationRecordDetail | null>(null), [detailError, setDetailError] = useState(''), [busy, setBusy] = useState(false), lock = useRef(false);
  const url = `${base}/records${query({ ...filters, page, limit: 10, search: term })}`;
  useEffect(() => { const timer = setTimeout(() => setTerm(search), 250); return () => clearTimeout(timer); }, [search]);
  useEffect(() => {
    const abort = new AbortController(); queueMicrotask(() => { if (!abort.signal.aborted) { setLoading(true); setError(''); } });
    api<PageResult<ValuationRecord>>(url, { signal: abort.signal }).then(value => { if (!abort.signal.aborted) setRows(value); }).catch(failure => { if (!abort.signal.aborted) { setRows(null); setError(failure instanceof Error ? failure.message : 'Không tải được lịch sử.'); } }).finally(() => { if (!abort.signal.aborted) setLoading(false); });
    return () => abort.abort();
  }, [url, reload]);
  useEffect(() => {
    if (!selected) return; const abort = new AbortController();
    api<ValuationRecordDetail>(`${base}/records/${selected}`, { signal: abort.signal }).then(value => { if (!abort.signal.aborted) { setDetail(value); setDetailError(''); } }).catch(failure => { if (!abort.signal.aborted) setDetailError(failure instanceof Error ? failure.message : 'Không tải được chi tiết.'); });
    return () => abort.abort();
  }, [selected, reload]);
  const columns: Column<ValuationRecord>[] = [
    { key: 'createdAt', label: 'Ngày định giá', render: row => dateTime(row.createdAt) }, { key: 'vehicleName', label: 'Xe', render: row => <span className="block max-w-64 whitespace-normal break-words">{row.vehicleName}</span> },
    { key: 'modelYear', label: 'Năm' }, { key: 'odometerKm', label: 'ODO', render: row => row.odometerKm === null ? 'Chưa rõ' : `${row.odometerKm.toLocaleString('vi-VN')} km` },
    { key: 'estimatedMarketValue', label: 'Giá ước lượng', render: row => money(row.estimatedMarketValue) }, { key: 'buyingMin', label: 'Khoảng thu mua', render: row => range(row.buyingMin, row.buyingMax) },
    { key: 'confidenceScore', label: 'Dữ liệu', render: row => `${row.confidenceScore}/100` }, { key: 'contactPhone', label: 'Liên hệ', render: row => row.leadId ? <span className="whitespace-nowrap">{row.contactName?.trim() && <>{row.contactName.trim()}<br /></>}{row.contactPhone}</span> : 'Chưa để lại thông tin' },
    { key: 'leadStatus', label: 'Xử lý', render: row => row.leadId && row.leadStatus ? leadStatusLabels[row.leadStatus] : 'Chưa có lead' }, { key: 'resultStatus', label: 'Kết quả', render: row => resultLabels[row.resultStatus] || row.resultStatus },
  ];
  const filterField = (key: keyof typeof blankFilters, label: string, type: string) => <Field label={label}><Input aria-label={label} type={type} value={draft[key]} min={type === 'number' ? 0 : undefined} step={type === 'number' ? 1 : undefined} onChange={event => setDraft(old => ({ ...old, [key]: event.target.value }))} /></Field>;
  if (selected) return <section className="tt-valuation__report space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">Chi tiết định giá</h2><Button variant="secondary" disabled={busy} onClick={() => { setSelected(''); setDetail(null); setDetailError(''); }}>Quay lại lịch sử</Button></div>
    {detailError ? <div role="alert"><p>{detailError}</p><Button variant="secondary" onClick={() => setReload(value => value + 1)}>Tải lại chi tiết</Button></div> : !detail ? <p role="status">Đang tải chi tiết…</p> : <>
      <h3 className="text-lg font-semibold">{detail.vehicleName} · {detail.modelYear}</h3><p className="text-sm text-[var(--muted-fg)]">{dateTime(detail.createdAt)} · Kết quả và quy tắc tại thời điểm định giá</p>
      <div className="grid gap-3 sm:grid-cols-2"><p>Giá tham chiếu: <strong>{money(detail.snapshot.result.referencePrice)}</strong></p><p>Giá ước lượng nội bộ: <strong>{money(detail.estimatedMarketValue)}</strong></p><p>Khoảng thị trường công khai: <strong>{range(detail.marketMin, detail.marketMax)}</strong></p><p>Khoảng thu mua công khai: <strong>{range(detail.buyingMin, detail.buyingMax)}</strong></p><p>Mức đầy đủ dữ liệu: <strong>{detail.confidenceScore}/100</strong></p><p>Kết quả: <strong>{resultLabels[detail.resultStatus]}</strong></p></div>
      {detail.snapshot.result.manualInspectionRequired && <div className="tt-valuation__note"><strong>Xe cần kiểm định trực tiếp.</strong><p>Các giá ứng viên nội bộ không phải giá đã báo cho khách.</p><ul>{detail.snapshot.result.reasons.map(reason => <li key={reason.code}>{reason.message}</li>)}</ul><p>Thị trường ứng viên: {detail.snapshot.result.candidateMarketRange ? range(detail.snapshot.result.candidateMarketRange.min, detail.snapshot.result.candidateMarketRange.max) : '—'}</p><p>Thu mua ứng viên: {detail.snapshot.result.candidateDealerBuyingRange ? range(detail.snapshot.result.candidateDealerBuyingRange.min, detail.snapshot.result.candidateDealerBuyingRange.max) : '—'}</p></div>}
      <section><h3 className="mb-3 text-lg font-bold">Thông tin đã cung cấp</h3><dl className="grid gap-3 sm:grid-cols-2"><div><dt>ODO</dt><dd>{detail.odometerKm === null ? 'Chưa rõ' : `${detail.odometerKm.toLocaleString('vi-VN')} km`}</dd></div>{Object.entries(conditionFields).map(([field, [category, label]]) => <div key={field}><dt>{label}</dt><dd className="font-semibold">{detail.snapshot.conditionOptions.find(option => option.category === category)?.label || 'Chưa rõ'}</dd></div>)}<div><dt>Số chủ</dt><dd>{detail.snapshot.input.ownerCount ?? 'Chưa rõ'}</dd></div><div><dt>Màu xe</dt><dd>{detail.snapshot.color?.name ?? 'Chưa rõ'}</dd></div></dl></section>
      <section><h3 className="mb-3 text-lg font-bold">Breakdown tại thời điểm định giá</h3><p className="mb-3 text-sm text-[var(--muted-fg)]">Snapshot đã lưu; không tính lại bằng quy tắc hiện tại. Tuổi xe: {detail.snapshot.result.ageYears} năm ({({ MODEL_YEAR: 'theo năm sản xuất', MANUFACTURING_DATE: 'theo ngày sản xuất', REGISTRATION_DATE: 'theo ngày đăng ký' } as Record<string, string>)[detail.snapshot.result.ageSource]}). ODO kỳ vọng: {detail.snapshot.result.expectedOdometerKm.toLocaleString('vi-VN')} km.</p>
        <div className="overflow-x-auto"><table className="tt-valuation-history-table"><thead><tr>{['Yếu tố', 'Quy tắc / phạm vi', '% cấu hình', '% áp dụng', 'Hệ số', 'Trước', 'Sau'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{detail.snapshot.result.adjustments.map((row, index) => <tr key={`${row.type}-${index}`}><td>{categoryLabels[row.type]}<br />{row.label}{row.manualInspectionRequired && <p>Cần kiểm định</p>}{row.fallback && <p>Dùng fallback</p>}</td><td>{row.ruleId ? `${row.ruleId} · ${row.scope ? scopeLabels[row.scope] : '—'}` : 'Không áp dụng rule'} </td><td>{row.configuredPercentage}%</td><td>{row.percentage}%</td><td>{row.factor}</td><td>{money(row.before)}</td><td>{money(row.after)}</td></tr>)}</tbody></table></div>
        {detail.snapshot.result.cap && <p className="mt-3 text-sm">Giới hạn: {money(detail.snapshot.result.cap.min)} – {money(detail.snapshot.result.cap.max)}; {detail.snapshot.result.cap.applied ? 'đã áp dụng' : 'không cần áp dụng'}.</p>}
        <details className="mt-4"><summary className="cursor-pointer font-semibold">Snapshot đầu vào, quy tắc và cấu hình đã áp dụng</summary><pre className="mt-3 max-h-96 overflow-auto rounded-xl bg-[var(--muted)] p-3 text-xs">{JSON.stringify(detail.snapshot, null, 2)}</pre></details>
      </section>
      {detail.snapshot.reference && <section><h3 className="text-lg font-bold">Nguồn giá đã lưu</h3><p>{baseTypeLabels[detail.snapshot.reference.basePriceType]} · {detail.snapshot.reference.source}</p><p className="whitespace-pre-wrap">{detail.snapshot.reference.note}</p><p>{detail.snapshot.reference.basisNote}</p></section>}
      <section className="border-t border-[var(--border-color)] pt-5"><h3 className="text-lg font-bold">Liên hệ và trạng thái xử lý</h3>{detail.contact ? <><p className="mt-2">{detail.contact.name?.trim() && `${detail.contact.name.trim()} · `}<a className="whitespace-nowrap text-red-600 underline" href={`tel:${detail.contact.phone}`}>{detail.contact.phone}</a></p><p className="my-3 whitespace-pre-wrap break-words">{detail.contact.content}</p><p>Trạng thái: {detail.leadStatus ? leadStatusLabels[detail.leadStatus] : '—'}</p>
        {canUpdate && <form key={detail.updatedAt} className="mt-4 grid gap-4 sm:grid-cols-2" onSubmit={async event => { event.preventDefault(); if (lock.current) return; const values = new FormData(event.currentTarget); lock.current = true; setBusy(true); try { const value = await api<ValuationRecordDetail>(`${base}/records/${detail.id}/status`, json('PATCH', { leadStatus: values.get('leadStatus'), reason: values.get('reason'), expectedUpdatedAt: detail.updatedAt })); setDetail(value); setReload(old => old + 1); toast.success('Đã cập nhật trạng thái xử lý.'); } catch (failure) { toast.error(failure instanceof Error ? failure.message : 'Không thể cập nhật.'); } finally { lock.current = false; setBusy(false); } }}><Field label="Trạng thái xử lý"><Select name="leadStatus" defaultValue={detail.leadStatus || 'NEW'} disabled={busy}>{Object.entries(leadStatusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Select></Field><Field label="Lý do cập nhật"><Input name="reason" required minLength={3} maxLength={1000} disabled={busy} /></Field><Button type="submit" disabled={busy}>{busy ? 'Đang lưu…' : 'Lưu trạng thái'}</Button></form>}
      </> : <p className="mt-2 text-[var(--muted-fg)]">Khách chưa để lại thông tin hoặc thông tin liên hệ đã được xóa.</p>}</section>
      <p className="tt-valuation__note">{detail.snapshot.disclaimer}</p>
    </>}
  </section>;
  return <section className="space-y-4"><h2 className="text-xl font-bold">Lịch sử định giá</h2><p className="text-sm text-[var(--muted-fg)]">Ngày lọc theo giờ Việt Nam; khoảng giá lọc là giá trị thị trường ước lượng nội bộ, đơn vị VND.</p>
    <form className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" onSubmit={event => { event.preventDefault(); setFilters(draft); setPage(1); setRows(null); setReload(old => old + 1); }}>
      {filterField('dateFrom', 'Từ ngày', 'date')}{filterField('dateTo', 'Đến ngày', 'date')}
      <Field label="Hãng xe"><Select value={draft.brandId} onChange={event => setDraft(old => ({ ...old, brandId: event.target.value, modelId: '' }))}><option value="">Tất cả hãng</option>{catalog.brands.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</Select></Field>
      <Field label="Dòng xe"><Select value={draft.modelId} onChange={event => setDraft(old => ({ ...old, modelId: event.target.value }))}><option value="">Tất cả dòng</option>{catalog.models.filter(row => !draft.brandId || row.brandId === draft.brandId).map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</Select></Field>
      <Field label="Trạng thái lead"><Select value={draft.leadStatus} onChange={event => setDraft(old => ({ ...old, leadStatus: event.target.value }))}><option value="">Tất cả trạng thái</option><option value="NONE">Chưa có lead</option>{Object.entries(leadStatusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Select></Field>
      {filterField('priceMin', 'Giá từ (VND)', 'number')}{filterField('priceMax', 'Giá đến (VND)', 'number')}
      <div className="flex items-end gap-2"><Button type="submit">Lọc lịch sử</Button><Button type="button" variant="secondary" onClick={() => { setDraft(blankFilters); setFilters(blankFilters); setSearch(''); setPage(1); setRows(null); setReload(old => old + 1); }}>Làm mới</Button></div>
    </form>
    {error ? <div role="alert"><p>{error}</p><Button variant="secondary" onClick={() => setReload(old => old + 1)}>Thử tải lại</Button></div> : <div aria-busy={loading}>{loading && <p role="status">Đang tải lịch sử…</p>}<DataTable<ValuationRecord> data={rows?.data ?? []} columns={columns} remote={{ page, total: rows?.meta.total ?? 0, perPage: 10, search, onPage: setPage, onSearch: value => { setSearch(value); setPage(1); } }} searchPlaceholder="Tìm tên xe, khách hàng hoặc số điện thoại…" emptyMessage={loading ? 'Đang tải…' : 'Chưa có lần định giá phù hợp.'} onView={row => { setSelected(row.id); setDetail(null); setDetailError(''); }} /></div>}
  </section>;
}
